[[Arrow]]
arch = "aarch64"
git-tree-sha1 = "3b9cf5ff3a63ab4694eb968ce8a7e84f20ea08bb"
os = "macos"

    [[Arrow.download]]
    sha256 = "1611cb340701d88dbe1ca687842ee946d0778218aadf14afc538e6faaaec6808"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.aarch64-apple-darwin.tar.gz"
[[Arrow]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91a8e77ef0a431dc70a05803ffc9bd13d1104d7b"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "abc97e9fb10569c5e3722940bd0f968714ba5dd93b18f789572cafef786d5493"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Arrow]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d34637c95ec99ea915101e97fe57f3bfc618d48a"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "1c37a618418e0574d82a9804a1d25ae957ebd90df1f8092fb9a1591c93b6e936"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5c577dcd8b7d83976229aff9a2ac108502352efc"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "21b239a27b15cf695b0444fe7debc4e2ef7572e84015796ae9e36a3300e6cbc6"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[Arrow]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af7993b4ea68a8aa94fa225bf38ea93fd24763e1"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "d80381bc6e6748179e41ab5b60880f7b576eaa2eed0d29bbebe55e5e22ce0914"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[Arrow]]
arch = "aarch64"
git-tree-sha1 = "24bf6dd26cd54d80b3ab2c683dc82595330c8960"
os = "freebsd"

    [[Arrow.download]]
    sha256 = "794717340a51f7375b5861848d2aeb2ef0e051e9960b073582b17efcba1d2758"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.aarch64-unknown-freebsd.tar.gz"
[[Arrow]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c2555a8ca168990c5a039c0eeaddc355af121675"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "efd67119ee86acb17efe42acfd39308b3c00b7c7438154ec669ec3cf3531b4be"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Arrow]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a6203b020d963c2cf6e02023bcb1967c6bd5f78"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "67cb26249bae0e0bcf017dc9682218a4e214c32cc0c2d783f0f55fb315744979"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Arrow]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "53006183c627e09be306dd8c97ac8741c280340d"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "c0ff92879146575a5bda32f6a6e1c69fb514e4bfd65cd0243d91ac92feb697e3"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Arrow]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f1a5aadf1669a83171cf3d247bfe373228ca331"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "96bad15a55247f978ea7d4781842aa3ad32f08fb382e6e3f0f5a5c5576b3e763"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Arrow]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "98bb472ea76e42279a43b17318938741b493e027"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "2306394ee2dceb6f99780846283dbf540feb12f5f57bdaf387a583e368bcf264"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Arrow]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fbbfd9a753c3d76c743772e8b5c0c5cba882ee74"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "3ce73cf34d1249eab1c27a632c7ad693f289ab97a0f71cd316363fec15ddc5f0"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Arrow]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8adddf8e9fe9c869bea3d9ff830539193e1a42b6"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "b8dd9f0e7797aacdde9ac14366e1a3adcf4e632565c12264736afd41ddfc1260"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Arrow]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a128aab5c52a75a65f04a1566f4aff1b04533b3"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "fba8e6376871fc05ed165e36d231a10ddb76554ad8e325f8e03ade73185f7789"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab266408d09ff5ac05d24d7374ffe015b71dac80"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "0cc65ac85fb802729f909aab34910bae0ed1285806344839e53c5e7c6efd82f3"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.i686-linux-gnu-cxx03.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b75cae2c33b53934fc30ad7befbb88b3fae07254"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "304ac4aa4c47c4197c2cd46db7cbdd6eefb45402aa0cc158fff569ffc71ccd4a"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.i686-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43c3b953c2aaf32d8fc30bc6723e0481223b9e10"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "a0883a549dc90b0d31d18f59a9006c6a6e7b6c7ffc6b20aa65594cd4193f3b04"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.i686-linux-musl-cxx03.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7831bc62bfed45c81d187e6644fffd16843b6895"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "12b573be60d1571b560b90150488222a5a1178921171ca96964f0d0f14dad928"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.i686-linux-musl-cxx11.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8759de7b67b66af901e7d51381ddc497453e809a"
os = "windows"

    [[Arrow.download]]
    sha256 = "d8231cfb9bb2609ddda9b442d02ee7126e4b9e8ebae9b9a05a342c46b7b94142"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64cca4f0ba564b5086d7746d38ffcf90db2df0f2"
os = "windows"

    [[Arrow.download]]
    sha256 = "1bdb8e4a5117cd26d919b4cc9e8e3373f40014f8a0d34ea4d2c4cc5a9f2c5592"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[Arrow]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "954c0bc3ed6578776a1c79dac93f42086e3feae4"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "15a6aa34d02c6fe5dde6eec53c766a5485acbf2f278c424aa1208a0af305fa34"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Arrow]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce12ceaa2c83da9848acf3d21dde0c024fde29d0"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "f91c18498ef0ab878800ca5cc971843fac724d6131a0b4f03947da653c61f6cf"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7090edded3bf2577e6c8f738693ac2347b16a110"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "1f5e5a17405fc02b81e04242d43aa76cf30e3b12e4b07cff1d389de832bb9f56"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.riscv64-linux-gnu-cxx03.tar.gz"
[[Arrow]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43ff3683395e3a79d8f405950a2e527a151cde8e"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "b8603a187a5e774b4af5aeb3db3646b4b4bfce10f73293ccb6074072e7490b88"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.riscv64-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "x86_64"
git-tree-sha1 = "bf1176ef7dc8ce0016e457c505f3c317721b8dee"
os = "macos"

    [[Arrow.download]]
    sha256 = "bd6145c9c33a29fb79de872c6eb1995cb4c22fb8fddcce88efd3957996ce3cc6"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.x86_64-apple-darwin.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b81ca9e5dcaab222452a792224ba4ac53e74db7"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "ac41ba4b93a206e103a33a7f9556315a0c46e835f34bf1ea0d42e4596cc3977a"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee71fbeb638c0b474504627b1abcc653b0c082a7"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "0025ba537659efd8ecb9c045331aab50f801acf5c46bfc17bdcbcb883a9b75ff"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "57e8c6c6ac82bf5ec8d09e06c36f795f4738cfd5"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "994a37e0cebb731a6fb677fe217b50e23f2827234eaa06685b27abc263f64ff4"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e4417f7a6d867b178fff8885e4c202117ee3595a"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "c42898bc09f8649e3a7322a97f31d4e88219b3c3adb7d7d865aa90c39f600db8"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[Arrow]]
arch = "x86_64"
git-tree-sha1 = "cb561a5549ee80abb29e3579d5a9d0e329a8df6a"
os = "freebsd"

    [[Arrow.download]]
    sha256 = "c629759193f63d66b61510a72dbfc429ca2ab00e954615af06c7758881b8ce92"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.x86_64-unknown-freebsd.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6dc05247061fa539be84ca403d6bfea57ee0a07"
os = "windows"

    [[Arrow.download]]
    sha256 = "c7f4093e2c5817c640bc16a8c0411f9dbf105a291c8a36d55f81f4b92284e802"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "902b750d17b37cd03f20cb1107f41b19812d232f"
os = "windows"

    [[Arrow.download]]
    sha256 = "8eadcbfa43ddba98d84f84d3a08465b8a39160af48067dcc60417c822a56cfa4"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.0+0/Arrow.v19.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
