[[Arrow]]
arch = "aarch64"
git-tree-sha1 = "be1aa93c25d99828ca0bac7eb01b74b97838ebb8"
os = "macos"

    [[Arrow.download]]
    sha256 = "64286cc722a19eca3708e06dc2f08b02cb5895c81000de6e32daf1756756f78a"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.aarch64-apple-darwin.tar.gz"
[[Arrow]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e8c0871198891cc2f47f5c0510277c6942ace4f5"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "47440e0b1a37d9e959210f1eb72b25ff4870474c78b542faa45dbbd796b06bb3"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Arrow]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c996c842dabcfc8c2d0ec7b16e8ecf2f2742ee7b"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "2055bcd32e770dcaf7e09dd9134ff49d416264228dcdc24c0e906d0a81b79bb1"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95618fbd3571074c01f337c8f3b439c599b4340a"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "e90d5ded69974551b249fb90d58c6c90108132a02aa7f5751c58a9ff097785bb"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.aarch64-linux-musl-cxx03.tar.gz"
[[Arrow]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9aeea39a3f74d5ae70ed24e91b814a66942fa81c"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "f632d0c1ad4b21c280e138f9b88a706cbcd3dba639adbacc5dd45975e785ca65"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.aarch64-linux-musl-cxx11.tar.gz"
[[Arrow]]
arch = "aarch64"
git-tree-sha1 = "ca996ce494215b3bd64b3c166ba24f2ea3403a62"
os = "freebsd"

    [[Arrow.download]]
    sha256 = "e53efa9ba3fce6b01d3559d10c3c8cccf424011a2990cf0c2ba28c75fbd1d383"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.aarch64-unknown-freebsd.tar.gz"
[[Arrow]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f8c91b06a8438e473193ccc8cd00e68bd7b475ae"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "a313fd416f63371492de515c8a6fbd0e7122fc35297eacb967cc0220fabce6f0"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Arrow]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dcfef1a4c9df3fb67016c406a832e11356ab1c58"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "0d5f811a759435a1c3dd3dbb276598f1172bea41db74111c750a2b82d263f085"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Arrow]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33f850919ab535a476cdfebf90c24cf420ac09f0"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "6d5a77c8641368dfed1aba91d3ac213aed6f1a2edcfd03eef70524e443b3766f"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Arrow]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "042af9bc6723632b6553fb99f016fd742fbe3346"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "38b2d6b8c30c3ec625d18108757d58cf87a6cf8640ebde61dc7a1bbfa3cb48f3"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Arrow]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f30856f236208261298dbe2bf3abbefa4e6cb49f"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "4437893f10e510563513cece033e2d74809d5aebfcfa7dec77893e58a7e2afcb"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Arrow]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a4f220b30addef6addbf20d104db566e2f4c0d8"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "8f3ef68fb53ff1214212e4a48a99c875fd71615680d7cab60ea7b700c1ac0985"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Arrow]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7ebd33d97c811c48f456e6eb279f1b5d588460d1"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "bacbe97b355e348c5d0a7dec6a22597086a7be9b628458c116520a9ab9f0ba60"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Arrow]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83adab40a56a21cab3904edbc37547cf20fd1a5e"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "d3fc022b4b7090d55484efe479d4f23bca7bb70cdbb9ac91fe465f6eb97473a6"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa10b018c28bf4797a8922382f3e6927410bb3c6"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "bf3cd135aca19c912e87c7bfa78f302363b4a66288474f5dcb05aba2e4af5bef"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.i686-linux-gnu-cxx03.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3f22c161e0bbf146fd2182c424ebfa9e6f8ce39"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "ecfe059c0bb707e8a123520cb467fe648b42593de755b654e756bf91ad236143"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.i686-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5e92dabfaa62cc5a0e398e7b2e15add9b3e1a9f4"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "5ae9148065bc757e8d17ab6900696228aa0ec115c66025f070bbcdcbd3ca300b"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.i686-linux-musl-cxx03.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "abd28b8609f06cc7547a3c58f2cfbc6033336ef1"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "09ad31a93d96f97039d96491acfe2df5e3e4f463541a1b9064ab5e3df2f17646"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.i686-linux-musl-cxx11.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "139032bff3b75b89f6a4e3f6834e00510527a330"
os = "windows"

    [[Arrow.download]]
    sha256 = "0e00fee60f4271933db786c837a25886c769d24e1bd3e1b940728cbc54b460d9"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d1bb3348102dafd1040740ab513d3cb1207ab14f"
os = "windows"

    [[Arrow.download]]
    sha256 = "66c0b398396382f71a1ab959bf4cac6cfd0074a91fc143044336d9fa962c8bfa"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[Arrow]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f946d88c97059f4d6af19159f3250343d17e230c"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "73329027e813972b11be1a52e071d6906e97c378679f9d27453130f19008a505"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Arrow]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "072f1958298e22b200d9535e24fab7d7380da36c"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "d10865117e13c0cc4385de2af19e744752efa65137e72f0aff34b9b99ac78bf2"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "x86_64"
git-tree-sha1 = "4d21dfd8c38ae3a67d433f2953e695f992bf312e"
os = "macos"

    [[Arrow.download]]
    sha256 = "61389234854e04cbe7b28386b59f7c4a35da5dcb365bcdcd241a395373d5ea54"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.x86_64-apple-darwin.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0f2089d43b1ff12fcffd4fbf3e240bac53e15f7f"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "d8af8160816ebf3ca694fe5f3d14a5801821c8a27bf242b8d5d22d5b30010b8e"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed76175c7ffa3cbfde758031680cfdf874359f9d"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "2de5e6d1e0e66008491a1d18fe933affeec1327879d06e06c427587afc76c158"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33c1a5be1f7f0e8e7dc33b0a64ac1de257b4323b"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "a53303db471378959a04c10bc033ebb386b59f4a38b237cc21224e73d3975a89"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5239d917eaf78485853e7a616c7637ddd2b0b1c5"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "4b35ea72dcf47de57761a43eb7e5fad8836a7188e089a5e86fd2c950a87a8e0f"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.x86_64-linux-musl-cxx11.tar.gz"
[[Arrow]]
arch = "x86_64"
git-tree-sha1 = "ca4c0a09b62985bda6da8749957f4b3cb2629870"
os = "freebsd"

    [[Arrow.download]]
    sha256 = "960c11cf3d7c97cf34c3e6531c31ad338e09569bf5177412c4e9dc98ad80e099"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.x86_64-unknown-freebsd.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8fc75d5fb8bc638c36e661cdc5a10cfff98fe718"
os = "windows"

    [[Arrow.download]]
    sha256 = "1b6ae8e19d3afc367f5c035931fa9cf76d918d276375d6ac21c7c3949389e9c2"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "66900769e5ae8a2ae77453b7b6bdfd5ad3207e2d"
os = "windows"

    [[Arrow.download]]
    sha256 = "e1d6a941e920036237995eccaeddc966d412eac47ad318d6978bd710a493b344"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.0+0/Arrow.v18.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
