[[Arrow]]
arch = "aarch64"
git-tree-sha1 = "099a122890ea5443cdd9649d54f41cdcbb1270ef"
os = "macos"

    [[Arrow.download]]
    sha256 = "ef63bb80b731c9c9b318f093232cdf003fb5f9cff7a5c1a751ba69d94d5bd723"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.aarch64-apple-darwin.tar.gz"
[[Arrow]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "644a873a687c74f79ad2bc1026d9ae738e47e8d9"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "033ebbd5592f200eb6a1636d1bc2ce18e16bc3076bc833fb450b77de2cf48621"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Arrow]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff4ec669907cb85d63e2cc2769f3a535e8aaf7d2"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "595e36f3e0cb2afc1831e6bae628c16dda0f490e9895f53c9e34bfa7a8a9b1fe"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dbf8c77f64cd308b804cdf4d3394a6e6e52b0498"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "660a37306abe130c767253c769fb84d42d0117e8ba3c4907287108dc4c334a5b"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Arrow]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "843b5c41dd9b3b0b8e051017ad5d57ee997aa174"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "4a70a068a9ece53b09f1892abb5e6aa1ee287fdc85f7586eedca5b503e378970"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Arrow]]
arch = "aarch64"
git-tree-sha1 = "14cc197dbb9f0f3f3e9df7fb324a4c4f2111a2be"
os = "freebsd"

    [[Arrow.download]]
    sha256 = "7245a61ee701fbae299bac166b0d3e21238d43a1f408e9f33f1c32dee59d3cf1"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.aarch64-unknown-freebsd.tar.gz"
[[Arrow]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0808fb4454169ae47c82bc250f36244d8e2528c7"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "467fa9dd52c320847cbda45284cc6ca1a1026a594b4fcd2b0ec5a24ddf471f60"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Arrow]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "61997d3616bb159dfd0406965eda90b37a598cfe"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "2b993ffd54b6eeeaa666a7de7218759ede7f7f1b5cc1471430004ff7dd7ebac4"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Arrow]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8cd0e9c2bb16ca5c68cd96d6898a05d8e150c17c"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "eccb979eff7ba08eaa12e7f13fd1f80781d5cd0618a8807a55b3b04cd74f4064"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Arrow]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be1882a29dbb560fec849ce37283129cc14df60d"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "97814bfba0d08beeffa051f2f7ddfcd61461750effb5b13d742a0b714faee411"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Arrow]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "47a19443aebbaf0125db89bc1c44c922d7eedd2f"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "7da3feb143b2154ae8f57226314fbbd3880b0db350a324788d680748353eb5fe"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Arrow]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a029b510392ce1edb178b23c50a30419bf2cff7"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "602f83ef312d2921afb8ce3b48bd65183402a473f8dd8be94145f77c8fa7ba95"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Arrow]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e361e545b7376a2dd0c1ac5378ae0ba26dd7dbcd"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "48092dec14024aae3b1a2dc4ce1f56b3336bab4d24cf6a5babc90ffb07e3ee11"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Arrow]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21c6d3504e0678c21a221842e4e3877443e3cbd9"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "c22114652fe0359d9f37dbef3df607792c4d97f6187d5a6eaabcece5021912e0"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ff673b7daa65d5eecb72bbc4ad92f15edd598b11"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "e30b00ac693a7383981fe9dd026badc0d214bb2ab0679737efb88214b2362eeb"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae2a14190655478b828afb068788b82056077edf"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "4779805a18970724c851b3292060d2034a531a6a03ff2a1567553499c282d326"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cab20701b7f8ba04a0c1ed8c65b0d268b8341928"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "78e1f5e132f6448467bf44f7f246bf3a3a63d3ca3884f4b85e587424f7b64faa"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.i686-linux-musl-cxx03.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9cde6107955fc79869202c8105759ab268ccdc50"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "443002d9681fdf39e342e68698b449d775fb8d6edbad95bd01037c9006e0ed0a"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.i686-linux-musl-cxx11.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c408735c36a4f252e69295ae9aee913a4af9b9a1"
os = "windows"

    [[Arrow.download]]
    sha256 = "05e02aaca78c2abaf8cc46fb9a32169166844fa325df5f92b5a0a3420b427668"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8850f43df3254ac924c340a3d9426305d4b9cc5c"
os = "windows"

    [[Arrow.download]]
    sha256 = "48f475cefabd5c4f19480fc1cf48aaea0580c9eb4da8372bef6e87dc33e44212"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Arrow]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3d4082cbf93a4add53d48525843415f3d05e488"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "5b4b10e82ca06d3e1976bdea354430f530453b492fce6030cde073d7317e49f7"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Arrow]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12155227c2555d50f152b2dc87692dbdcd614ba7"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "b0e05bc7ae7959f99139e84ca5cddd5d08d1a62ed199e8d9ef94e4ee36ed69f1"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "936c2b5c76298ffc37c714b83434048268aad1f5"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "c9668eb0422e89ea88dd052eb49dbe79cd8dfe7c36bae3a797ec0f88da698031"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.riscv64-linux-gnu-cxx03.tar.gz"
[[Arrow]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18dd2c8c7625f76842e08226c107cedc1747e475"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "350b69a0657907b14bf4e332eabcba1b6f0f763ccbaec538a2218babfa72fcb1"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.riscv64-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "x86_64"
git-tree-sha1 = "b1f6d901f71f5ac10cd0930ac51592c7f751423b"
os = "macos"

    [[Arrow.download]]
    sha256 = "4af332bf86cd1aed7cebbaa8810f622cdbe67d1ae59ec6186b92ad5bbb6a8805"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.x86_64-apple-darwin.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "13b51e372ea7d7a02fcee136ed83f9f2c80d8147"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "2510e717f88cdbb1eae10e24ac89cc6c7515bd29a2bbab9bf01d9975c0fd54a8"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ed71247665c9c1e9f67122e3bf44cef97113c8d"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "40c31f87d28cefe5678a231fd53a8862b0a8ce7df197f6144b82f0770f29447b"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d733166398b9ef2cf76570216aff6e339a87e87f"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "eaaec1294767eeec7bd1f4271b87cfd361e559938705329441d9b81e50156855"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ba09ff8aa23c51e9e81c90d6826b2be38075acf"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "8252d41ab981c42ed76378f31b5d9d58a0d6ef67b2adc116bc853e3c08fffcd3"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Arrow]]
arch = "x86_64"
git-tree-sha1 = "3efcb66c876cb5c98d18522b036f06b28fa613b7"
os = "freebsd"

    [[Arrow.download]]
    sha256 = "2d7dee81c753e2945dee8d2bab5edadac88063bd2c0fb0cb55eb89200931a09e"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.x86_64-unknown-freebsd.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1258827227b4c00270747b2dc4720d157a380102"
os = "windows"

    [[Arrow.download]]
    sha256 = "f440764593f7c717d3888a4186a8979c358436e2743e15eb8f53ddaae8d25428"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48a6f0d676b4fae29247c77dbd7105fd26b46f37"
os = "windows"

    [[Arrow.download]]
    sha256 = "d5c1ae10495f7486b111d6054f234d7712b182bd22d145652aaaaeeccc7cb76d"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v19.0.1+0/Arrow.v19.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
