[[Arrow]]
arch = "aarch64"
git-tree-sha1 = "3dc1fb7ea241bfe7ba9484f348746363413c1ef3"
os = "macos"

    [[Arrow.download]]
    sha256 = "9c54d284632497d67bb023a98792dc43d0064194438628af13899d92bd3300f7"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.aarch64-apple-darwin.tar.gz"
[[Arrow]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5b845913d6b7e041df8c33be37e203fb8e7ff937"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "d1b60e9a1a09561567600d87ab940dee3bc4ff801e1fbfdbf0d1d324dd4ae183"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Arrow]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5cfc52ff67fb36a49948db0b2e6a4eb6454f0359"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "d6c716dee8784f67846e6f9b85828a80a996f70db8729a68f6a0dea529a812e6"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1237f9cedfc7dab4a8ec9c1afe7f1119b78def49"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "0ee391f85d290e34aeb5eb19354d27447434d6050c5bd6a0267e41391ffb328d"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[Arrow]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12057db5cb00b62152c933cdde42c48f3f79526d"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "a6e5ed90f58c0b03130a5852b122cfcf0cffa82d1cfb945271a3929b04093843"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[Arrow]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d9599d58c82cc7d81dbb60611eff2add95b3c44"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "b8907c43e67adc04d2fca2b14542a82d930b9b9d5683400986407fb54bc9a8db"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Arrow]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7716439200a751788ee13699a6c735c8c8db656f"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "9afee32a1840e7ab6716c98c6ad8210a3db8402ba8c1f6f25a6c4b130e2a1446"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Arrow]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bac6831adb11cdac4228c47d18ed3bfb5a2b2652"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "5ce2584575f445054b513d1a9d7a5792fae4bc5e94c97e387b1a60709e57c67e"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Arrow]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de0a0b2bcdb50ac2188f6dd4454b5bbf396876ae"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "4776f8a39f967de95c93ff7a23d638029a8c3d8206322d34a1354e321989d0e4"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Arrow]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6be7866307c5c6bffe41e0e4811805f861d42a54"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "800f1454fe331458d374f134c5090919320772e00a8d9e5976f1a185418366b0"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Arrow]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2efd374087e0a8c4652c259c6282ad7688dfb8da"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "1686e2dd7f623d1c456cbe3a3f78584ad0d091f7f68d0eb37e07c6fa64823cf0"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Arrow]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8159de7aaeb954b8cf70e17c16ba922ce5dcf294"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "f75ea38caf13100b25e7c6da8501b7089acc0fa4ecd80b211ec1d7bdcb2c6113"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Arrow]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8139439a3ef38c140159b9ed2c9395730ce3b45d"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "39b4c501f8593e6e8c8ae3fcf2d536179c98977939706a13bc1ce8471e244de5"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1403916b5edd40acc10a2112bb5243db8a2217d5"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "213c6078bd10078da8da80ee46ac464532b2adeca97107d896caeb011126b023"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.i686-linux-gnu-cxx03.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "27561e24332584f93a3fbfd45603253565f58ec2"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "d3d381b660f1fa1a3587be69caa00ef855ea37989d8054ff95e78032c6053fe8"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.i686-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4efb0e83738c788f0067ca634e67771b35a06bbb"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "6938c4e72ef8d671fcd5d2986b8bee5574c8c84fa32e9550fdbf886d9fcb8caf"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.i686-linux-musl-cxx03.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95ceb1f19c71c2eed02d9c44d51474526eec2ed7"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "9d6565995ab437504f2bb96b71d53cd0f4b27ae72e937d0594f21e769e48b324"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.i686-linux-musl-cxx11.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8c1b2b6c818c964b03813b9951f9feae0c419597"
os = "windows"

    [[Arrow.download]]
    sha256 = "c4cef92dce28ce33f23fd29e9224a6a5ed39d36d6e971baa3cfa0e5527c9a7aa"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a68f5185931eaf51ff0035334bfcc880ce01f7b"
os = "windows"

    [[Arrow.download]]
    sha256 = "d1cdc9a0e6d174e654f9dd2d05b4169e4f4995f2b1c4dcdaedb00614b11eef7d"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[Arrow]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "778270f056bbea80551fbc6cdff87bae00eddadb"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "02cdbabec5ce496e1c4ce02a04159cbb4f78d0c4a04cceebcbd4e87cfab2119d"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Arrow]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b5c98857d841734e06cd3dbb20285b4339d770a4"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "1662985a3cb7bc087c0195a1d4963fd28732e159d66730fbd929f3a5d0d96fc2"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "x86_64"
git-tree-sha1 = "8fdd6b95668e2c77c0be8330902b4636131704c2"
os = "macos"

    [[Arrow.download]]
    sha256 = "133aa4d52d2c17d1fa5bf87e76964cf6cbbe3a3159621c4e9038485625c6b69b"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.x86_64-apple-darwin.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "05f21a95f99307f3511a5473173da03775cbaa71"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "ca58baed347c55800fbf75cae70e480abde4de23181bd874145aca183a063e59"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "531277f9923dc8ff11431ede7778f8e3a4e14a7a"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "2e05437a79bdc6281a51e718537482846ae0361d698fb0e3b83b46504b75a43d"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b11c561999e4164908c7c2b54630aa80d4417099"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "c52573acc60388f5a0f03bc98629ef7765640c2d699ecf9d54625dd4dda082b6"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bdcd18d8b2c59b4e2b36b13a3c31287e4d49c8fa"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "86e534adff853575ab1440d6fc6fc0493d5523b6802948e30014de057de3ca88"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[Arrow]]
arch = "x86_64"
git-tree-sha1 = "5d677c36bf1edfe0b6a25112cb06bf1d02573131"
os = "freebsd"

    [[Arrow.download]]
    sha256 = "827469b114bfbedd67e1431ceb736db81a5036ffbadd2da9fd7ef0ba8035c2d4"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.x86_64-unknown-freebsd.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94a206f2c9f4badcfb4ea289de6f1a34e7340a27"
os = "windows"

    [[Arrow.download]]
    sha256 = "3641ab28133c31fe77021737ab6895de2b18bc6d853523771af3830cf9a22893"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "401a7179c8e42af85c5cc87cc9326d5b8e5db9b6"
os = "windows"

    [[Arrow.download]]
    sha256 = "beacedc647268d1c6ea86498d3a37cb33a7ffbcc9266df6e7f696a68be4ac852"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v10.0.0+0/Arrow.v10.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
