[[Arrow]]
arch = "aarch64"
git-tree-sha1 = "8a025d65932a2f1447cf153ff6fc1463ad6d25d8"
os = "macos"

    [[Arrow.download]]
    sha256 = "d195d01c58f8eebb0c5ccbd2851681b62d79c5dfb77f0d5481cdcd19db93d943"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.aarch64-apple-darwin.tar.gz"
[[Arrow]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0ce4718e404c2a2c748e72d5f731e44e8eb192be"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "f96b1e0e5612a2f07b40f40961fc47b159331219610d514322b32195941d419f"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Arrow]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29d299bb7920714e5cb4eec77c9db449228b8f22"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "bc1318a2f668de8274796d96a4a0394bbd4cfebc4a34d632151133dfd59bc047"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "718bcd8b1742e14294223e6167f8510895d92387"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "71a8c726ca67869aa4eb634eb62b6441a779151b5859256978f69f40b1333045"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.aarch64-linux-musl-cxx03.tar.gz"
[[Arrow]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "646239558289fabd8690e383dccad70237c32db6"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "1f3ec47d82aeae9b5c0c296df66a017802e112109ae6817f490b39590d91d3fb"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.aarch64-linux-musl-cxx11.tar.gz"
[[Arrow]]
arch = "aarch64"
git-tree-sha1 = "3d3be4585891e16d8b1ea1958be0105f409a9f2d"
os = "freebsd"

    [[Arrow.download]]
    sha256 = "0f395d7ce4bbb3000d1e42e44d38996d30df113676a0d55cf436d2d255299111"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.aarch64-unknown-freebsd.tar.gz"
[[Arrow]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9355825741868717fb3a11b5224e8be56d45353c"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "404e961190dbb0e6ec9414064d068070e1de4013d50592c88607bf42222f5a3a"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Arrow]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "17220c9a1c9cd24de5aaf85e664340383cd5b858"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "18ec5615802ed0f09f1f215ed3167358fa136da0cc644664db3143474a6e7d8c"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Arrow]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c76ad11d5e93a141d172a2a6530a18b28897bbad"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "521f6e9f3170e0b6e6e7c510eeab1d9b43531bdab546a9b80da10b8ea71ceced"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Arrow]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2276856ffe3ee75e2bcba175e0bcc4334f2ee568"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "6cf38177cb002495ea8e1730a8a815751e09eac21103b4b1b5055272cffb6774"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Arrow]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "608a44d2391e02899471dde160189c9649dbb8cd"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "89a3a9bc8ba7afa88d5874e5b4dacbc9cc265819ce5709e84fa16dc1c90fe766"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Arrow]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e4bcd1a9ea5b64e781007d7fb0e6ea4a4d2d711b"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "fc36b43c88b2fecd1d58528629cedd4e3d1abad8f3443a1ad30b38bbe48ec41f"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Arrow]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c0bf96df1d70501a4cc15b1665c0b393ee68f970"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "880c33ca46c3981b58e59ead3241c04aaefb17db6673d585b4698a6cbbc7a2a7"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Arrow]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dee0b525d08c2edfb39a35dea9cd719b1aca6c88"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "0fb3815498fe53c200f4727df5fd89daba566b7c8beec3d6ba960a73e2f84fe3"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "48bf26498e08712336c13acd76937384e923a61a"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "a632147e0880af5801641caf3e3695a01c830e5f992f336bfd195a97edc1807f"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.i686-linux-gnu-cxx03.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0212a67fd02ae7ad879013dea40d4bef06606983"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "11e0f76a1a5ba01755433f20bb01cedea25304ddbd1d2f467150f5e637d34292"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.i686-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "beb6c4553261f4d7c2c70afc8cd56a72655c2562"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "fe76b2ea85a4a256ff4f00ac85a9537470e52b20723f873d3b52172ba6967b5a"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.i686-linux-musl-cxx03.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1297a377071d92e7a8de9e79cfd52f0bebb2ea6"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "5a0fa5e07d1fd89fa7be04feac595949c71f01102705c4f5d681225872aa6d9a"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.i686-linux-musl-cxx11.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b69d658b605df6b858f80e9f44bf362784a37c3d"
os = "windows"

    [[Arrow.download]]
    sha256 = "a5bdcfaf8e35c83ee862fd30c3938f37bd0c375d5d89f2e75d890071bd58e6cd"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.i686-w64-mingw32-cxx03.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43609e2176abdba50fe329e26b9abae41f0cb768"
os = "windows"

    [[Arrow.download]]
    sha256 = "ee354fd23b2219b0379686f2e8cabe96157ad910e5d9d5c4d22b422b0cb39627"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.i686-w64-mingw32-cxx11.tar.gz"
[[Arrow]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "752d16a3877f05c66a3093d139dfb67f35a67dc4"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "5f4fb141f2b0450647619fca2fd602769a408647617c1aa5fa0ab471d37e1c28"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Arrow]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ef65b0202c6d83be474f58c0c17217a7e68fe43"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "483781a6cca1c352ac050365fba8eaefd3dc0c22bfb5736fb74abe75b1ba3fda"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "x86_64"
git-tree-sha1 = "69e978865c45294f367456a5a6835b11898aa87d"
os = "macos"

    [[Arrow.download]]
    sha256 = "d8b14ac2e13008a1528c43f171f45cc822aa1e15f7a35a4fb4e24d0bb127ef4b"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.x86_64-apple-darwin.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "003f72d017ca5b58f0ad8725b726194b18a50afc"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "005682a2562355f42eaf12704d1c3e9534ce66eea3c6fd55e5f9872d9ea93fed"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c278c988579dbf1ba08c8a5d32a0d3b356eda0e"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "4119496584d0f4eee34ddcb4cd302f5d237cd080dab458ab6473f1ba7a2f019a"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "127927801a3df9e5269737d4f0f0d9ca4ce0c42d"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "01410cd65fc2562b9bfdae54a84e4a3be50d5f9eb34e8f10ed5a8a32c28ea51d"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.x86_64-linux-musl-cxx03.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b113483c59629bd47b6831fcaa6d96dd3c584c1b"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "30723f39e6c8078b46d31c6685b656ccfa63fcf8db41c0293be884dff9d77cb0"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.x86_64-linux-musl-cxx11.tar.gz"
[[Arrow]]
arch = "x86_64"
git-tree-sha1 = "5b4af9efd6da90914ce0416f74d5c92e4d0fb2d9"
os = "freebsd"

    [[Arrow.download]]
    sha256 = "be17ebb63277d6e538d758dbbfa906e84d069dc0528ba9a417c16787fd9abe59"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.x86_64-unknown-freebsd.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "074b2f3bda3e107d4eff9ea37c308376ec18cd79"
os = "windows"

    [[Arrow.download]]
    sha256 = "351e1b4f1a38c6cb2a90b4c10aee7f1f149d5f7fb0348eae83134828dac0127b"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2983af8bfc11e2f3da9321edfd598eb62e72da6"
os = "windows"

    [[Arrow.download]]
    sha256 = "3a226fbff4a32a8b12976b399616c1bc323687e8d748ddff953721122a7cbc6f"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v18.1.1+0/Arrow.v18.1.1.x86_64-w64-mingw32-cxx11.tar.gz"
