[[Arrow]]
arch = "aarch64"
git-tree-sha1 = "e73768bf6d5ad5565d5520a212292703c96ae6a0"
os = "macos"

    [[Arrow.download]]
    sha256 = "2398641553b466f167adee901fc6148b8e835a92648870748a9a849e55a2735e"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v24.0.0+0/Arrow.v24.0.0.aarch64-apple-darwin.tar.gz"
[[Arrow]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e94aa8f0bb75095d10de41f2f9eb0c31090505fb"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "a615b16bf71c8610a40c19b4a2377f3bd9158dd7631a86d31b081630a807b9dc"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v24.0.0+0/Arrow.v24.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64ba3dff9faf43e30b427db7a311e22d1a3906fd"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "2be9d555e3c24f2038d28ee14eba447fa16cc4ed47c597a934b43ea744d150d6"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v24.0.0+0/Arrow.v24.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[Arrow]]
arch = "aarch64"
git-tree-sha1 = "27863357bf1372a1b8d03eb6b266406609513cb0"
os = "freebsd"

    [[Arrow.download]]
    sha256 = "3bb035408208e64be022e030bd3a1a44625c8db46421b020c7d7ff25caffde33"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v24.0.0+0/Arrow.v24.0.0.aarch64-unknown-freebsd.tar.gz"
[[Arrow]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d8f1cdc5b425fccc31096eb49f9fb995a90577e"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "209924e70e0cceb47511376d3da2b1649822eca14e29c2717b15578e82ccf19e"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v24.0.0+0/Arrow.v24.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Arrow]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "acfa94c29fdcf65026044b7e2807c44424587b41"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "94e039ab9b07d14d814b592fad1ace591e5036c3ba336496668a88c2cc3b3162"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v24.0.0+0/Arrow.v24.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Arrow]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd464df4f1b4f9bf0ebd64b1f3cad7522e372028"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "151e764f067d1d36568f40b4653317c1c656bba8d070805c2586a724cede6394"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v24.0.0+0/Arrow.v24.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Arrow]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5248ecbfbfc67e42d34cf4cb37d0bc4f3177bfb6"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "dff1190503a92b1b5dbc7705670ac773a83223aecdadb003e1bde36fae4746b6"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v24.0.0+0/Arrow.v24.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "300eeaffa60b93e5bb087e230141cd111c0a119d"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "4e43e2aadc170e577622c6f61695db0037d9e6a9b38b801810badb66d578e078"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v24.0.0+0/Arrow.v24.0.0.i686-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d2f1a6fdb28a812b164c3528cbaf5c76654a7a8"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "a4fe9c2228eadce9cfe70527bdd0ae06db0b79ee4ffb732d1d858d23b37e06e7"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v24.0.0+0/Arrow.v24.0.0.i686-linux-musl-cxx11.tar.gz"
[[Arrow]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6709297d81018955af7aacda214d38d09ca94093"
os = "windows"

    [[Arrow.download]]
    sha256 = "bed3ebd9d65700cbd096474d5c5933761e7caa033168e83676c5930a25f49137"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v24.0.0+0/Arrow.v24.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[Arrow]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3afa61cfc26a5c0c728e44b3b2cd52718ece18a5"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "ffc9cc78d381385931a5cef3090528429503f6d3a75ce02bbd1cc922daad8bc0"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v24.0.0+0/Arrow.v24.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5f959beae8215a82080801ce3729f52e8499fe3"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "0c86a190f1d8fdf3e7313ad2ff66b7fe7659258d489ebbd9e74d9ddc4cab6b16"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v24.0.0+0/Arrow.v24.0.0.riscv64-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "x86_64"
git-tree-sha1 = "7263a1bc26729ec44eb84db91442b4b263f5a473"
os = "macos"

    [[Arrow.download]]
    sha256 = "df85fdc7bb8ec66c564857d89ec2c88efdaf2f486e4af287441c3d51179b003c"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v24.0.0+0/Arrow.v24.0.0.x86_64-apple-darwin.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1614fa31e331dfc71a07d91b5a3d8f24c6e54675"
libc = "glibc"
os = "linux"

    [[Arrow.download]]
    sha256 = "f6f88ff403d010507e71d1f082891d44871c2dce25d09ee974d1b40497104f44"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v24.0.0+0/Arrow.v24.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ad711357030da401136c0876b3751fcf457a8ab"
libc = "musl"
os = "linux"

    [[Arrow.download]]
    sha256 = "4d1e09d4304be50b4e14352429c4511c9a235913ae94b9c23da99672d6a89c4c"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v24.0.0+0/Arrow.v24.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[Arrow]]
arch = "x86_64"
git-tree-sha1 = "bc09f9f7e04920ddc18939b861f56d6e4a276962"
os = "freebsd"

    [[Arrow.download]]
    sha256 = "a29027e9fdaa0545d28230712911fad7be45d5ea425219df8f0c81b0bbd9aef6"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v24.0.0+0/Arrow.v24.0.0.x86_64-unknown-freebsd.tar.gz"
[[Arrow]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bda57983b1e0ea1fee0d06764f05f1d2381fbcd4"
os = "windows"

    [[Arrow.download]]
    sha256 = "9580cff55f3c202ed6bf26310d3443de2de7979c669cc7f80664b4744d13c48a"
    url = "https://github.com/JuliaBinaryWrappers/Arrow_jll.jl/releases/download/Arrow-v24.0.0+0/Arrow.v24.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
