# Autogenerated wrapper script for Arrow_jll for i686-w64-mingw32-cxx11
export libarrow, libarrow_dataset, libparquet

using Bzip2_jll
using CompilerSupportLibraries_jll
using Lz4_jll
using Thrift_jll
using Zlib_jll
using Zstd_jll
using boost_jll
using brotli_jll
using snappy_jll
JLLWrappers.@generate_wrapper_header("Arrow")
JLLWrappers.@declare_library_product(libarrow, "libarrow.dll")
JLLWrappers.@declare_library_product(libarrow_dataset, "libarrow_dataset.dll")
JLLWrappers.@declare_library_product(libparquet, "libparquet.dll")
function __init__()
    JLLWrappers.@generate_init_header(Bzip2_jll, CompilerSupportLibraries_jll, Lz4_jll, Thrift_jll, Zlib_jll, Zstd_jll, boost_jll, brotli_jll, snappy_jll)
    JLLWrappers.@init_library_product(
        libarrow,
        "bin\\libarrow.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libarrow_dataset,
        "bin\\libarrow_dataset.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libparquet,
        "bin\\libparquet.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
